apiVersion: v2
name: amd-gpu
description: A Helm chart for deploying Kubernetes AMD GPU device plugin
type: application
home: https://github.com/ROCm/k8s-device-plugin
sources:
  - https://github.com/ROCm/k8s-device-plugin
icon: https://raw.githubusercontent.com/ROCm/k8s-device-plugin/master/helm/logo.png
maintainers:
  - name: Kenny Ho <Kenny.Ho@amd.com>
keywords:
  - kubernetes
  - cluster
  - hardware
  - gpu

kubeVersion: ">= 1.18.0-0"
version: 0.16.0
appVersion: "1.31.0.2"

dependencies:
- name: node-feature-discovery
  version: ">= 0.8.1-0"
  repository: "https://kubernetes-sigs.github.io/node-feature-discovery/charts"
  condition: nfd.enabled
