nfd:
  enabled: false

labeller:
  enabled: false

dp:
  image:
    repository: docker.io/rocm/k8s-device-plugin
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.31.0.2"
  resources: {}

lbl:
  image:
    repository: docker.io/rocm/k8s-device-plugin
    tag: "labeller-1.31.0.2"
  serviceAccount:
    annotations: {}
  securityContext:
    privileged: true # Needed for /dev
    capabilities:
      drop:
        - ALL
      add:
        - CAP_SYS_ADMIN
    readOnlyRootFilesystem: false # true if -logtostderr flag set in labeller
  # If you do want to specify resources, uncomment the following lines, 
  # adjust them as necessary, and remove the curly braces after 'resources:'.
  resources: {}
    # limits:
    #   memory: 20Mi
    #   cpu: 100m
    # requests:
    #   memory: 30Mi
    #   cpu: 150m

imagePullSecrets: []

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists

node_selector_enabled: false
node_selector:
  feature.node.kubernetes.io/pci-0300_1002.present: "true"
  kubernetes.io/arch: amd64
