apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}-device-plugin-daemonset
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      name: {{ .Chart.Name }}-dp-ds
  {{- with .Values.dp.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        name: {{ .Chart.Name }}-dp-ds
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.node_selector_enabled }}
      {{- with .Values.node_selector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      priorityClassName: system-node-critical
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-dp-cntr
          image: {{ .Values.dp.image.repository }}:{{ .Values.dp.image.tag | default .Chart.AppVersion }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: dp
              mountPath: /var/lib/kubelet/device-plugins
            - name: sys
              mountPath: /sys
            - name: health
              mountPath: /var/lib/amd-metrics-exporter/
          resources:
            {{- toYaml .Values.dp.resources | nindent 12 }}
      volumes:
        - name: dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: sys
          hostPath:
            path: /sys
        - name: health
          hostPath:
            path: /var/lib/amd-metrics-exporter/
            type : DirectoryOrCreate
